version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: donet-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - donet-net

  blue-server:
    image: jangikhwan/donet-be
    container_name: blue-server
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - donet-net

  green-server:
    image: jangikhwan/donet-be
    container_name: green-server
    ports:
      - "8082:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - donet-net

volumes:
  dbdata:

networks:
  donet-net: {}
